#!/bin/bash
cd /03-student/hw/Lucky_Duck_Investigations/Roulette_Loss_Investigation/Dealer_Analysis
sed s/'05:00:00 AM'/sus_0315_5am/ 0315_Dealer_schedule > 0315_sustimes.txt
sed s/'08:00:00 AM'/sus_0315_8am/ 0315_Dealer_schedule >> 0315_sustimes.txt
sed s/'02:00:00 PM'/sus_0315_2pm/ 0315_Dealer_schedule >> 0315_sustimes.txt
grep sus 0315_sustimes.txt > Dealers_working_during_losses_0315
